docker network connect monitoring-net monitoring-lab-app
docker network connect monitoring-net prometheus
docker network connect monitoring-net jaeger
docker network connect monitoring-net alertmanager
docker network connect monitoring-net grafana 
docker network connect monitoring-net redis
docker network connect monitoring-net redis-exporter
docker network connect monitoring-net postgres
docker network connect monitoring-net postgres-exporter
docker network connect monitoring-net loki
docker network connect monitoring-net promtail
